---
- name: "s3_exporter | Deploy s3_exporter service configuration"
  ansible.builtin.template:
    src: "s3_exporter.service.j2"
    dest: "{{ '/etc/systemd/system/' + vars['s3_exporter_service'] +
      '.service' }}"
    owner: "root"
    group: "root"
    mode: "0644"
  notify:
    - "Daemon reload"
    - "Restart s3_exporter"
- name: "s3_exporter | Enable s3_exporter"
  ansible.builtin.systemd:
    name: "{{ vars['s3_exporter_service'] }}"
    enabled: "yes"
  when:
    - "hostvars[inventory_hostname]['s3_exporter'] is defined"
    - "hostvars[inventory_hostname]['s3_exporter'] != ''"
    - "hostvars[inventory_hostname]['s3_exporter'] |
       community.general.json_query(vars['s3_exporter_enable']) is defined"
    - "hostvars[inventory_hostname]['s3_exporter'] |
       community.general.json_query(vars['s3_exporter_enable']) == 'true'"
  vars:
    s3_exporter_enable: "[] | map(&enable || 'false', @) | [0]"
